### ISSUE TITLE
TypeError: render is not a function

### ISSUE THREAD

**Issue by chbert** [srmullen/sveltekit-magic#1]
Thanks for all the work @srmullen !

I'm trying to run a copy of your repo but I run into a TypeError.

**How to reproduce**

1. clone project
2. pnpm install
3. pnpm run dev
4. open localhost:300 in browser

**Output**
`SvelteKit v1.0.0-next.119

  local:   http://localhost:3000
  network: not exposed

  Use --host to expose server to other devices on this network

render is not a function
TypeError: render is not a function
    at Object.handle (/Users/user/Workspace/sveltekit-magic/src/hooks.ts:17:31)
    at async respond (file:///Users/user/Workspace/sveltekit-magic/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.119_svelte@3.38.3/node_modules/@sveltejs/kit/dist/ssr.js:1515:10)
    at async Immediate.<anonymous> (file:///Users/user/Workspace/sveltekit-magic/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.119_svelte@3.38.3/node_modules/@sveltejs/kit/dist/chunks/index.js:3330:23)`

**Comment by srmullen** [comment]
Thanks for bringing this to my attention.

Newer versions of SvelteKit have renamed the `render` function to `resolve`. I'll push a fix for that soon.

**Comment by chbert** [comment]
Thanks for the quick response @srmullen ! I should've checked the sveltekit docs 😄

**Comment by srmullen** [comment]
Fixed!
